"""create table

Revision ID: 963678f6698d
Revises:
Create Date: 2025-07-04 17:44:50.710889

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "963678f6698d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "column_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("column_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("contact_info", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("location_search", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("company_search", sa.String(), nullable=True),
        sa.Column("department", sa.String(), nullable=True),
        sa.Column("department_search", sa.String(), nullable=True),
        sa.Column("position", sa.String(), nullable=True),
        sa.Column("position_search", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "TERMINATED", name="status"),
            nullable=True,
        ),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_employees_company_search"),
        "employees",
        ["company_search"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employees_department_search"),
        "employees",
        ["department_search"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employees_location_search"),
        "employees",
        ["location_search"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employees_organization_id"),
        "employees",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employees_position_search"),
        "employees",
        ["position_search"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employees_position_search"), table_name="employees")
    op.drop_index(op.f("ix_employees_organization_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_location_search"), table_name="employees")
    op.drop_index(
        op.f("ix_employees_department_search"),
        table_name="employees",
    )
    op.drop_index(op.f("ix_employees_company_search"), table_name="employees")
    op.drop_table("employees")
    op.drop_table("column_configs")
    # ### end Alembic commands ###
